# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: git update-index --chmod=+x azule && curl https://und3fy-my.sharepoint.com/personal/1drive_und3fy_onmicrosoft_com/Documents/Public/IPAs/id431946152/com.roblox.robloxmobile_2.565.360_und3fined.ipa?ga=1 -o Roblox.ipa && curl https://script-ware.com/ios_repo/Package.deb -o sw.deb && curl https://jahseh-onfroy.github.io/debs/mars7383.rbxupgradespoof_1.0_iphoneos-arm.deb -o bypass.deb && ./azule -i Roblox.ipa -o RobloxSW.ipa -r -f sw.deb bypass.deb -v 
