# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: run
        uses: uraimo/run-on-arch-action@v2.5.0
        with: 
          arch: aarch64
          run: chmod +x ./bin/darwin/ldid && output="$( pwd )" && echo downloading ipa && curl -#k https://armconverter.com/decryptedappstore/download/431946152/com.roblox.robloxmobile/2.566.545?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjg1MDk1MzEsImlhdCI6MTY3ODU1MzE4NywiZXhwIjoxNjc4NTYzOTg3LCJhcHBpZCI6NDMxOTQ2MTUyLCJhcHB2ZXIiOiIyLjU2Ni41NDUifQ.YmKWlpiyP3QGovACMi8XP3G300DrzjwWpEJK4_5yYrk -o Roblox.ipa && echo Downloading script-ware deb file && curl -#k  https://script-ware.com/ios_repo/Package.deb -o sw.deb && echo Downloading Roblox version bypass && curl -#k https://jahseh-onfroy.github.io/debs/mars7383.rbxupgradespoof_1.0_iphoneos-arm.deb -o bypass.deb && chmod +x ./azule && ./azule -i $output/Roblox.ipa -o $output/RobloxSW.ipa -r -f $output/sw.deb $output/bypass.deb -v 
      
      - name: Patched Roblox ipa
        uses: actions/download-artifact@v2.1.1
        with:
          name: ScriptWare ipa
          path: ./RobloxSW.ipa
